### ISSUE TITLE
Import error in Extra module

### ISSUE THREAD

**Issue by Maxtodont** [dottedmag/pychm#23]
```
Traceback (most recent call last):
  File "chmparser.py", line 188, in <module>
    chm_obj = ChmParser(file)
  File "chmparser.py", line 25, in __init__
    if not self.chm.LoadCHM(filepath):
  File "/home/test/anaconda3/envs/Salomon/lib/python3.7/site-packages/chm/chm.py", line 221, in LoadCHM
    self.GetArchiveInfo()
  File "/home/test/anaconda3/envs/Salomon/lib/python3.7/site-packages/chm/chm.py", line 317, in GetArchiveInfo
    self.lcid = extra.get_lcid(self.file)
  File "/home/test/anaconda3/envs/Salomon/lib/python3.7/site-packages/chm/extra.py", line 32, in get_lcid
    return struct.unpack('<i', content)
NameError: name 'struct' is not defined
```

**Comment by dottedmag** [comment]
Thanks, this is a very rare codepath.

By any chance, could you share .chm file to have a testcase?

**Comment by Maxtodont** [comment]
https://www.virustotal.com/gui/file/c3962e7b5abcd6ebbf0fb37d0b18f0450cb33cf2dc4dc5dbfd199e6130269872

**Comment by dottedmag** [comment]
I couldn't find the download link at that page. Could you attach the file to this issue?

**Comment by Maxtodont** [comment]
[import_error_chm.zip](https://github.com/dottedmag/pychm/files/10386433/import_error_chm.zip)

**Comment by dottedmag** [comment]
Thanks, fixed in master. This CHM seems to be properly converted by https://github.com/dottedmag/archmage now.
